import Head from 'next/head'
import Image from 'next/image'
import { Roboto} from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'


const roboto = Roboto({ subsets:['greek'] ,weight:"100"})

export default function Home() {


const router = useRouter();


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className={"bg-gray-100 flex items-center justify-center w-screen h-screen"}>

      <div  className={"text-lg flex flex-row gap-2  text-gray-900"+roboto.className}>

          
      <button
      
      onClick={()=>router.push('/doctor')}
      
      
       className={"bg-blue-500 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded"}>
        Doctor
      </button>
      <button className={"bg-green-500 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded"}>
       Patient
      </button>
      <button className={"bg-violet-500 hover:bg-violet-700 text-white font-semibold py-2 px-4 rounded"}>
     signup
      </button>
      <button className={"bg-slate-500 hover:bg-slate-700 text-white font-semibold py-2 px-4 rounded"}>
        login
      </button>
      <button className={"bg-cyan-500 hover:bg-cyan-700 text-black font-semibold py-2 px-4 rounded"}>
       medical
      </button>
     


      </div>
        

       



      </main>
    </>
  )
}
